# Generated by Django 5.2.17 on 2026-10-10 16:52

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_unit_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_change", models.IntegerField()),
                ("stock_before", models.PositiveIntegerField()),
                ("stock_after", models.PositiveIntegerField()),
                ("note", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_adjustments",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity_change", 0), _negated=True),
                        name="inventory_adjustment_nonzero_change",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "stock_after",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("stock_before"),
                                    "+",
                                    models.F("quantity_change"),
                                ),
                            )
                        ),
                        name="inventory_adjustment_stock_matches_change",
                    ),
                ],
            },
        ),
    ]
