# Generated by Django 5.1.15 on 2026-09-28 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horizon_days", models.PositiveIntegerField()),
                (
                    "values_json",
                    models.JSONField(help_text="List of predicted units for day 1..N"),
                ),
                (
                    "model_name",
                    models.CharField(default="RandomForestRegressor", max_length=100),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_forecasts",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "horizon_days", "-generated_at"],
                        name="forecasting_product_03165a_idx",
                    )
                ],
            },
        ),
    ]
