# Generated by Django 5.1.15 on 2026-09-28 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReorderRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_daily_demand", models.FloatField()),
                ("supplier_lead_time", models.PositiveIntegerField()),
                ("safety_stock", models.IntegerField()),
                ("reorder_point", models.FloatField()),
                (
                    "forecast_demand",
                    models.FloatField(
                        help_text="Forecasted demand used for the reorder qty calc"
                    ),
                ),
                ("current_stock", models.IntegerField()),
                ("recommended_quantity", models.IntegerField()),
                ("reorder_required", models.BooleanField(default=False)),
                ("explanation", models.TextField(blank=True)),
                ("is_simulation", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reorder_recommendations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"],
                        name="recommendat_product_668535_idx",
                    )
                ],
            },
        ),
    ]
